### PR TITLE
Issue 17: Fix datatype of ShaclIn

### PR DESCRIPTION
**Pull request by yashkhatri**
Changed datatype of ShaclIn to String array. In addition to this fixed more minor bugs.

### CODE REVIEW

**Review by jadelkhoury — APPROVED** [review]
Looks good to me

**Comment by jadelkhoury** [comment]
This request is approved. Trying to work out how to merge it!

**Comment by jadelkhoury** [comment]
@berezovskyi help! I don't seem to find the "merge" button

**Comment by berezovskyi** [comment]
image

**Comment by berezovskyi** [comment]
image

**Comment by jadelkhoury** [comment]
I could see "rebase and merge". but never "confirm rebase and merge". I am using Firefox. I will try another browser just in case.
Thanks!

**Comment by berezovskyi** [comment]
Confirm button only appears after you click the first one.

–Andrew.
(sent from my phone)

**Pull request merged**
