### PR TITLE
Initial contribution

### LINKED ISSUE #1: Initial contribution
Move from https://git.eclipse.org/r/#/c/101273/

### PR DESCRIPTION
**Pull request by berezovskyi**
Closes #1 

TODOs:

- [x] @berezovskyi merge conflict https://git.eclipse.org/r/#/c/111123/
- [x] @berezovskyi incorp Jad's review remarks https://git.eclipse.org/r/#/c/111123/
- [x] File all CQs under https://bugs.eclipse.org/bugs/show_bug.cgi?id=519639
- [x] Await https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14724
- [x] @jadelkhoury review pull request
- [ ] @jamsden review pull request
- [x] @yashskhatri approve EPL+EDL license header

### CODE REVIEW

**Comment by berezovskyi** [comment]
Build is OK, but only with the https://git.eclipse.org/r/#/c/111123/ merged in. I will rerun the build again then.

**Comment by berezovskyi** [comment]
@yashkhatri, we had to switch the license back again from EPL to EPL plus EDL as required by Eclipse Lyo project, apparently. Yash, please check the patch and reply here that you are OK with the change to the license header.

The CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13872 has approved release under EPL and EDL already.

**Comment by berezovskyi** [comment]
Now that the patch to core has been merged in Gerrit, this build succeeds as well.

What do I need from you guys:

- [x] Yash @yashskhatri has to comment here and approve that the copyright header now grants a license not only under EPL but under EPL&EDL.
- [x] @jadelkhoury has to approve the review.

**Comment by yashkhatri** [comment]
Yes, it is okay!

**Review by jadelkhoury — APPROVED** [review]

**Pull request merged**
